### ISSUE TITLE
Emulator builtin busybox tar may fail to set permissions

### ISSUE THREAD

**Issue by stefaang** [nzbget/android#3]
> I/Daemon: stdout: Installer for nzbget-19.1
I/Daemon: stdout: Verifying package...
I/Daemon: stdout: Checking system...
I/Daemon: stdout: CPU-Architecture: i686
I/Daemon: stdout: Unpacking...
I/Daemon: stdout: tar: chown 1001:1001 '7za-i686': Operation not permitted
I/Daemon: stdout: tar: chown 1001:1001 'cacert.pem': Operation not permitted
I/Daemon: stdout: tar: chown 1001:1001 'ChangeLog': Operation not permitted
...
I/Daemon: stdout: tar: chown 1001:1001 'webui/index.js': Operation not permitted
I/Daemon: stdout: tar: chown 1001:1001 'webui/fasttable.js': Operation not permitted
I/Daemon: stdout: tar: chown 1001:1001 'webui/nzbget.conf.template': Operation not permitted
I/Daemon: stdout: ERROR: Unpacking failed.

When using the builtin busybox of Android Studio, the tar command fails when setting the permissions.
As everything is unpacked already, this is not a big deal, but the installer configure step is skipped.
I got around it by adding the following commands

    # this is already in libdaemon.so, evt add --nocheck if your platform needs it
    sh $INSTALLER --destdir $HOME/nzbget >> $DAEMONLOG 2>&1
    # remove the unpack command from the installer
    sed '/Unpacking failed/d' -i $INSTALLER
    # get the new header size
    sed '/END-OF-INSTALLER/q' $INSTALLER > install.sh
    HEADERSIZE=`du -k install.sh | cut -f1`
    sed 's:^HEADER=\d+:HEADER=$HEADERSIZE:' -i $INSTALLER
    rm install.sh
    # run the installer again to configure the app, skipping the CRC check and unpack phase
    sh $INSTALLER --destdir $HOME/nzbget --nocheck >> $DAEMONLOG 2>&1

Ideally this should be fixed in the nzbget installer upstream.
*I mean that the installer could use a separate configure argument, to be used after the unpack-only phase.

This little hack removes the dependency of the packaged libbusybox.so, allowing it to execute on any architecture (in the current state, only ARM is supported).

**Comment by hugbug** [comment]
Are you following the installation manual https://nzbget.net/installation-on-android when you get this error?

**Comment by stefaang** [comment]
I was trying to build the installer for x86 with API 24 for a headless android device when I faced this issue.
Unfortunately I'd missed the emulator instructions you provided.
However I wanted to cover the install on a device without using root.
This is how I tested it:

    adb shell
    run-as net.nzbget.nzbget
    sh installer.run ...

**Comment by hugbug** [comment]
Is this an emulator or a real device with x86 CPU?

**Comment by stefaang** [comment]
The results here are on the x86 emulator... 

The headless device has an ARM CPU but I have very limited access to it at the moment.. so I focused development on the emulator. I was adapting the installer to work through a web interface (instead of the screen). The user has no root access.

I just realized what went wrong: I started development on the x64 emulator. The installer failed to use busybox as the 64bit version is not in the package. However my emulator had busybox in its /system/bin so I wanted to use that one... but there I met the tar - chown permission issue.

I realise my modifications are not on-topic for the current android nzbget installer, I just wanted to share my solution to get around the tar permission issue in android MM when using the emulator builtin bb.

**Comment by hugbug** [comment]
No root is required when using the installer app.

If you work with device directly via terminal/ssh then you don't need the installer app at all. Just run the nzbget installer. But you need a good busybox as the default shell is too limited.

However a headless android device - does it make any sense? Why not a linux device then?

**Comment by stefaang** [comment]
This is the result with the packaged (in this project) busybox:

> generic_x86:/data/data/net.nzbget.nzbget $ cat daemon.log
Installing daemon
Installer for nzbget-19.1
Verifying package...
Segmentation fault
Installer for nzbget-19.1
Checking system...
Segmentation fault
Segmentation fault
CPU-Architecture: i686
Unpacking...
Segmentation fault
Installation successful

This is why I wanted to use the builtin busybox instead of the packaged one.

**Comment by stefaang** [comment]
Don't bother about the sense of a headless android device ;) 
Something with easier application management for the vendor and tighter security (no root).
But it's always nice to have nzbget on a headless device with a lot storage space.

Anyway, the default busybox/toolbox has a broken tar command for non-root users as it tries to chown the unpacked files. And in the previous post you see my issues with the packaged version.

**Comment by hugbug** [comment]
Root isn't needed for installer.

The x86 busybox may be indeed broken as I haven't tested it due to lack of x86 android devices. I'm not sure if a test in emulator is a proper test for it though.

Does nzbget installer work with your busybox if you do "su" first?
Does `chown` work (as regular user and as admin)? If it doesn't then the system is broken, I would say. 

BTW the configure step in installer is just a nice to have feature which isn't necessary. You could unpack installer on a linux machine and then copy the files to the box.

Anyway I can't alter the behavior of `tar`. So I think there is nothing I can do here.

**Comment by stefaang** [comment]
`su` is not possible in 'a production environment' for the default emulator (nexus 5X).
On the pixel emulator I met another issue with platform parsing, see my MR.
After bypassing that I was able to `su` and do the regular install.
However I prefer to use the `run-as net.nzbget.nzbget` shell to track the user permission limits.

Sure, you can't modify the tar behavior, but I could use a 'ignore_tar_exceptions' installer option here.

Edit: I broke header size by replacing that line. That still needs to be fixed.

**Comment by hugbug** [comment]
>I could use a 'ignore_tar_exceptions' installer option here.

I think we have a special case here which isn't worth changes in nzbget installer. You can install nzbget on desktop and then move the whole directory to device or use your trick.

Sure, if it would be more popular to install nzbget on emulator... but you are probably the only one who did this in two years since this possibility is available.

Nonetheless, if you do think the change is worth it - please submit a PR and I'll merge it 👍.
`--ignore_tar_exceptions` seems to be a bit long. Maybe `--notarcheck`, similar to existing `--nocheck`?

Still, why `chown` fails? It's a normal command not requiring root.

**Comment by stefaang** [comment]
Default tar behavior is to unpack files with current user as owner. The emulator builtin busybox tar apparently uses chown to do this last step.
Anyway, I have a workaround and I won't pollute your installer for this unlikely scenario.

**Comment by stefaang** [comment]
Root cause of this problem: android M ships with busybox and toybox... it uses toybox tar and sed instead of the busybox versions.
