### ISSUE TITLE
Feature Request: Forcibly keep daemon running in the background

### ISSUE THREAD

**Issue by ghost** [nzbget/android#4]
Sometimes, the daemon gets closed in the background, even on devices with 2 GB of RAM. This results in unexpected: "Communication Error! Cannot establish connection to NZBGet" in the browser I am using, which is currently Brave Browser. 

Any means of keeping the daemon from being closed in the background until the user explicitly closes it would be great. 

Perhaps a notification that the daemon is running? A high priority setting?

**Comment by hugbug** [comment]
> Sometimes, the daemon gets closed in the background

NZBGet never closes itself. It is either closed on a user request or it crashed. The latter must be investigated but I need more info.

**Comment by ghost** [comment]
@hugbug I know it never closes itself, but it's not always closed by user request or a crash. Sometimes, Android will close background apps depending on the device, how much RAM it has, how Android has been configured by the OEM, or some other configuration that can only be changed by rooting. 

We need a way to guarantee that Android cannot close the daemon while its running in the background,

**Comment by hugbug** [comment]
NZBGet daemon isn't an android app running in background, neither is it an android background task. It is a Linux process running as background process. Android task manager has no means to control such processes and therefore cannot terminate it.

Task manager can terminate NZBGet UI app but the daemon will continue running. If the daemon terminates it is either closed by an user action (via NZBGet webui) or the process crashed.

Install debug version of the daemon, enable all logging and after it terminates inspect the logs.

**Comment by ghost** [comment]
@hugbug Ah I see. I will do that. Closing issue since I misunderstood how the daemon works.
